#! /bin/sh

# Accuweather RSS feed reader for Conky

# Fahrenheit (0) or Celsius(1)?
METRIC=0

if [ -z $1 ]; then
	echo
	echo "USAGE: weather <LocationCode>"
	echo
	exit 0;
fi

curl -s http://rss.accuweather.com/rss/liveweather_rss.asp\?metric\=${METRIC}\&locCode\=$1 | 
	grep '<title>Currently:' | head -n 1 |
	perl -ne '/Currently: (.*)\</; print $1'
